
The following have been reloaded with a version change:
  1) FFTW/3.3.8-gompic-2019b => FFTW/3.3.8-gompi-2019b
  2) OpenMPI/3.1.4-gcccuda-2019b => OpenMPI/3.1.4-GCC-8.3.0
  3) ScaLAPACK/2.0.2-gompic-2019b => ScaLAPACK/2.0.2-gompi-2019b
  4) SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4 => SciPy-bundle/2019.10-foss-2019b-Python-3.7.4


The following have been reloaded with a version change:
  1) SciPy-bundle/2019.10-foss-2019b-Python-3.7.4 => SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4

--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[50733,1],0] (PID 24755)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
2020-05-12 08:44:07.881068: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1

START MCDO
Process Process-1:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "use_Arrays.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "use_Arrays.py", line 677, in MCDO
    method_main()
  File "use_Arrays.py", line 666, in method_main
    test_on_own_func(METHODNAME, mcdo_own_predictions, y_test)
  File "use_Arrays.py", line 374, in test_on_own_func
    acc = accuracy_score(y_test.argmax(axis=1), mean_predictions_all)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 71, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1399, 350]

START MCBN
Process Process-2:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "use_Arrays.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "use_Arrays.py", line 747, in MCBN
    method_main()
  File "use_Arrays.py", line 736, in method_main
    test_on_own_func(METHODNAME, MCBN_own_predictions, y_test)
  File "use_Arrays.py", line 374, in test_on_own_func
    acc = accuracy_score(y_test.argmax(axis=1), mean_predictions_all)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 71, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1399, 350]

START Ensemble
Dataset_name: MES, N_folders: 2, total mebers: 70
Process Process-3:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "use_Arrays.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "use_Arrays.py", line 821, in Ensemble
    method_main()
  File "use_Arrays.py", line 810, in method_main
    test_on_own_func(METHODNAME, Ensemble_own_predictions, y_test)
  File "use_Arrays.py", line 374, in test_on_own_func
    acc = accuracy_score(y_test.argmax(axis=1), mean_predictions_all)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/metrics/classification.py", line 71, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/software/software/scikit-learn/0.21.3-foss-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1399, 350]

START VarianceOutput
2020-05-12 08:44:34.387511: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-12 08:44:34.414247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-05-12 08:44:34.414329: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-12 08:44:34.418180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-12 08:44:34.420906: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-12 08:44:34.422035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-12 08:44:34.424810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-12 08:44:34.426334: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-12 08:44:34.431502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-12 08:44:34.433736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-05-12 08:44:34.440233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: Tesla K40m computeCapability: 3.5
coreClock: 0.745GHz coreCount: 15 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 268.58GiB/s
2020-05-12 08:44:34.440283: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-12 08:44:34.440324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-12 08:44:34.440364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-05-12 08:44:34.440403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-05-12 08:44:34.440463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-05-12 08:44:34.440514: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-05-12 08:44:34.440555: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-12 08:44:34.442864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-05-12 08:44:34.442915: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-12 08:44:34.903045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-12 08:44:34.903146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0 
2020-05-12 08:44:34.903168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N 
2020-05-12 08:44:34.906605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10741 MB memory) -> physical GPU (device: 0, name: Tesla K40m, pci bus id: 0000:03:00.0, compute capability: 3.5)
2020-05-12 08:44:34.907065: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.
Accuracy on original test dataset: 4.3%
tf.Tensor(
[[   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [1033  104   98  104   60]], shape=(5, 5), dtype=int32)
Correct: 60, wrong: 1339, accuracy: 4.288777698355969%

Mean probability on true label of original test dataset when correctly predicted = 67.16%
Mean uncertainty on true label of original test dataset when correctly predicted = 13.24%
Mean probability on true label of original test dataset when wrongly predicted = 2.47%
Mean uncertainty on true label of original test dataset when wrongly predicted = 20.91%

Mean probability on highest predicted on original test dataset when wrong = 86.04%
Mean uncertainty on highest predicted on original test dataset when wrong = 14.66%

Mean probability on all not true label on original test dataset = 23.69%
Mean uncertainty on all not true label on original test dataset = 18.31%
creating scatterplot
Process Process-4:
Traceback (most recent call last):
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/software/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "use_Arrays.py", line 49, in with_profiling
    ret = fn(*args, **kwargs)
  File "use_Arrays.py", line 890, in VarianceOutput
    method_main()
  File "use_Arrays.py", line 885, in method_main
    Error_new_predictions = np.load('Error_MNIST.npy')
  File "/software/software/SciPy-bundle/2019.10-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Error_MNIST.npy'

#################################
Function main called 1 times. 
Execution time max: 13.250, average: 13.250
#################################


###############################################################################
Peregrine Cluster
Job 11385876 for user 's2934833'
Finished at: Tue May 12 08:44:41 CEST 2020

Job details:
============

Name                : CombArrays
User                : s2934833
Partition           : gpu
Nodes               : pg-gpu04
Cores               : 12
State               : COMPLETED
Submit              : 2020-05-12T08:43:52
Start               : 2020-05-12T08:44:03
End                 : 2020-05-12T08:44:41
Reserved walltime   : 00:30:00
Used walltime       : 00:00:38
Used CPU time       : 00:00:13 (efficiency:  2.95%)
% User (Computation): 46.96%
% System (I/O)      : 53.04%
Mem reserved        : 8000M/node
Max Mem used        : 1.62G (pg-gpu04)
Max Disk Write      : 194.56K (pg-gpu04)
Max Disk Read       : 7.13M (pg-gpu04)
Average GPU usage   : 0.0% (pg-gpu04)


Acknowledgements:
=================

Please see this page for information about acknowledging Peregrine in your publications:

https://wiki.hpc.rug.nl/peregrine/additional_information/scientific_output

################################################################################
